### ISSUE TITLE
normalizeFileReplacements(...).pipe is not a function with Angular 7.2

### ISSUE THREAD

**Issue by hebra** [enten/udk#8]
After upgrading from Angular 7.1.x to the just released 7.2 the build with UDK fails throwing the following exception:

```
normalizeFileReplacements(...).pipe is not a function
TypeError: normalizeFileReplacements(...).pipe is not a function
    at supportFileReplacement (/Users/heb/devel/my-project/node_modules/udk/angular/lib/udk-builder.js:32:68)
    at MergeMapSubscriber._getBuilderConfig.pipe.operators_1.concatMap [as project] (/Users/heb/devel/my-project/node_modules/udk/angular/lib/udk-builder.js:175:41)
    at MergeMapSubscriber._tryNext (/Users/heb/devel/my-project/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/Users/heb/devel/my-project/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/Users/heb/devel/my-project/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (/Users/heb/devel/my-project/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/Users/heb/devel/my-project/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/heb/devel/my-project/node_modules/rxjs/internal/Subscriber.js:67:18)
    at /Users/heb/devel/my-project/node_modules/rxjs/internal/util/subscribeTo.js:17:28
    at Object.subscribeToResult (/Users/heb/devel/my-project/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
    at MergeMapSubscriber._innerSub (/Users/heb/devel/my-project/node_modules/rxjs/internal/operators/mergeMap.js:82:29)
    at MergeMapSubscriber._tryNext (/Users/heb/devel/my-project/node_modules/rxjs/internal/operators/mergeMap.js:76:14)
    at MergeMapSubscriber._next (/Users/heb/devel/my-project/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/Users/heb/devel/my-project/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (/Users/heb/devel/my-project/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/Users/heb/devel/my-project/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/heb/devel/my-project/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (/Users/heb/devel/my-project/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/Users/heb/devel/my-project/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (/Users/heb/devel/my-project/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/Users/heb/devel/my-project/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/heb/devel/my-project/node_modules/rxjs/internal/Subscriber.js:67:18)
```

[package.json.txt](https://github.com/enten/udk/files/2740418/package.json.txt)

**Comment by enten** [comment]
Thanks for reporting this issue.

The error is due to commit [angular-cli/eaad125d](https://github.com/angular/angular-cli/commit/eaad125da9e50e0cacdeb42f2daa5c643fcc7629#diff-0a63610d8a5ecb3a69f15116259ddbb8L41) which changes `normalizeFileReplacements` and `normalizeAssetPatterns` returns type and commit [4f8a5b7a](https://github.com/angular/angular-cli/commit/4f8a5b7a#diff-168988bada076544b0ac8442acc73a72R11) which introduces `normalizeOptimization`.

We need to refactor [udk-builder](https://github.com/enten/udk/blob/master/angular/lib/udk-builder.ts) to be compat with angular 7.2.

I will do that soon.

**Comment by enten** [comment]
@hebra 

I published [udk v1.0.1](https://github.com/enten/udk/tree/v1.0.1) to [support angular-devkit/build-angular v0.12.x](https://github.com/enten/udk/commit/80d1e28834824bd48b2f298018650a09ce5d1c75).

**Can you try `npm install udk@1.0.1` and give us a feedback if the issue is resolved?**

**Comment by hebra** [comment]
@enten yes, it is working with 1.0.1 - thanks a lot for the quick issue resolution.

**Comment by enten** [comment]
@hebra 
My bad, I don't consider commit [8516d682](https://github.com/angular/angular-cli/commit/8516d68213f4bafd34b5c68dfde43462173f5603#diff-bcaf070bc0c9af879278aa6fb7502894R19) which introduces `normalizeSourceMaps`.

Therefore source map doesn't work with [udk v1.0.1](https://github.com/enten/udk/tree/v1.0.1).

I published [v1.0.2](https://github.com/enten/udk/tree/v1.0.2) to [fix source map](https://github.com/enten/udk/commit/b928d718afd83720096776f0bbb899a28b19517e).

**Can you update udk to v1.0.2 and tell us if source map works again?**

**Comment by hebra** [comment]
@enten I can confirm that 1.0.2 still works as expected with Angular 7.2

**Comment by enten** [comment]
@hebra Thanks for your feedback.
